# `dependabot.yml` file with
# customized schedule for version updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/src/ApplicationInsghts.Demo/Api"
      - "/src/ApplicationInsghts.Demo/Web"
      - "/src/OpenTelemetry.Demo/Api"
      - "/src/OpenTelemetry.Demo/Web"
      - "/src/Others/ConsoleApp"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Asia/Tokyo"
