using '../templates/functions_user_assigned_managedIdentity.bicep'

param managedIdentityName = 'uami-fy25q3-test-3ak'
param storageAccountName = 'stfy25q3test3ak'
param newOrExisting = 'new'
param workspaceName = 'log-fy25q3-test-5ak'
param appInsightsName ='appi-fy25q3-test-5ak'
param planName = 'plan-fy25q3-test-3ak'
param functionName = 'func-fy25q3-test-3ak'
param location = 'westus2'
