@baseUrl = https://apim-test-3.azure-api.net/test-3
@token = 
@tenantId = 73bc7a90-849a-45f9-be6c-d5ca3b068fad

GET {{baseUrl}}/api/category?tenantId={{tenantId}}
Content-Type: application/json
Authorization: Bearer {{token}}
Ocp-Apim-Subscription-Key: e304d27c48e643549205093265ca96cc
