name: Deploy SQL Database Project

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: self-hosted
    env:
      PROJ_PATH: './src/SqlSampleDb'
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
        
      - name: Build DACPAC
        run: dotnet build ${{ env.PROJ_PATH }}/SqlSampleDb.sqlproj -c Release
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: db-project
          path: ${{ env.PROJ_PATH}}/bin/Release

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: db-project

      - name: Deploy DACPAC to Azure
        uses: azure/sql-action@2.2
        with:
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          path: './SqlSampleDb.dacpac'
          action: 'Publish'
          arguments: '/p:DropObjectsNotInSource=false'
      
      - name: Logout from Azure
        run: az logout
