name: Deploy API to Azure Functions

on:
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'リソース グループ名'
        default: 'rg-test-3'
        required: true
        type: string
      webAppName:
        description: '関数アプリ名'
        default: 'func-test-3'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      APP_PATH: './src/FuncProj'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Publish
        run: |
          cd ${{ env.APP_PATH }}
          ls