name: Deploy API to Azure Functions

on:
  workflow_dispatch:
    inputs:
      sourcePath:
        description: '展開するソースのパス'
        required: true
        default: './src/AzureFunctions/FuncProj'
        type: choice
        options:
          - './src/AzureFunctions/FuncProj'
          - './src/AzureFunctions/FuncProjIntAspNet'
          - './src/AzureFunctions/FuncCustomClaimProvider'
      resourceGroup:
        description: 'リソース グループ名'
        default: 'rg-test-3'
        required: true
        type: string
      functionAppName:
        description: '関数アプリ名'
        default: 'func-test-3'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      APP_PATH: ${{ github.event.inputs.sourcePath }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true
      
      - name: Build with dotnet
        shell: bash
        run: |
          pushd './${{ env.APP_PATH }}'
          dotnet build -c Release -o ./funcapp
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Function app Publish
        uses: Azure/functions-action@v1
        id: deploy-to-azure-function
        with:
          app-name: ${{ github.event.inputs.functionAppName }}
          package: ${{ env.APP_PATH }}/funcapp
          sku: flexconsumption
          remote-build: false